version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: deploy/Dockerfile
      target: api
    restart: always
    ports:
      - "${API_PORT:-8000}:80"
    env_file:
      - .env
    volumes:
      - ./static:/app/static
    depends_on:
      db:
        condition: service_started

  db:
    ports:
      - "${DB_PORT:-5832}:5432"
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: "${DB_NAME:-rocknblock}"
      POSTGRES_USER: "${DB_USER:-rocknblock}"
      POSTGRES_PASSWORD: "${DB_PASSWORD:-rocknblock}"
    command: postgres -c 'max_connections=${DB_MAX_CONNECTIONS:-1000}'
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-rocknblock} -d ${DB_NAME:-rocknblock}"]
      interval: "${HC_INTERVAL:-10s}"
      timeout: "${HC_TIMEOUT:-10s}"
      retries: 5
      start_period: 10s
    restart: unless-stopped


volumes:
  db-data:
