# Generated by Django 5.0.2 on 2024-02-18 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TokenModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_hash', models.TextField(unique=True)),
                ('tx_hash', models.TextField(blank=True, null=True)),
                ('media_url', models.URLField(unique=True)),
                ('owner', models.CharField(max_length=42)),
            ],
        ),
    ]
